name: Docker Build and Push to Aliyun ACR

on:
  workflow_dispatch:
    # 允许在任意分支手动触发
    branches: [ '*' ]

jobs:
  build-and-push:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

      
    - name: Login to Aliyun ACR
      run: echo ${{ secrets.ALIYUN_ACR_PASSWORD }} | docker login --username=围巾jj --password-stdin crpi-6044uvgap7p6k5ne.cn-hangzhou.personal.cr.aliyuncs.com
       
    - name: Build and push Docker image
      run: |
        DOCKER_TAG=$(date +'%Y%m%d%H%M')
        # docker run --privileged --rm tonistiigi/binfmt --install all
        docker build -tcrpi-6044uvgap7p6k5ne.cn-hangzhou.personal.cr.aliyuncs.com/ywj_720/ollama:0.6.1 .
        docker push crpi-6044uvgap7p6k5ne.cn-hangzhou.personal.cr.aliyuncs.com/ywj_720/ollama:0.6.1
      env:
        DOCKER_USERNAME: 围巾jj # 对于阿里云Acr，使用_json_key作为用户名
        DOCKER_PASSWORD: ${{ secrets.ALIYUN_CR_PUBLISH_PASSWORD }} # 引用GitHub Secrets中存储的密码
